### ISSUE TITLE
Compatibility Magento 2.3

### ISSUE THREAD

**Issue by Axel29** [PH2M/logistic#5]
Hello,

Do you have a patch planned for Magento 2.3.x?
In your composer.json, there's a require for "magento/product-community-edition": "~2.1.0|~2.2.0".

Thank you,

Axel

**Comment by VincentMarmiesse** [comment]
Hi @Axel29,

It should be ok now with version 1.0.6, can you try and let me know?

**Comment by Axel29** [comment]
Hello @VincentMarmiesse,

Thank you for the update.
